#Code used in the preparation of data for 
#“Factors associated with COVID-19 outbreaks in Immigration and Customs Enforcement (ICE) Detention Centers” 
#in The American Journal of Public Health (doi: ***)

#starting data set is from the COVID Prison Project, available at https://github.com/healthandjustice/covid-prison-project/tree/main/data

#necessary libraries
library(tidyverse)
library(readxl)
library(cgwtools)

#get weekly cases from full case data
#df is a data frame of all of the cases at facilities of interest from COVID Prison Project
#save result as new dataframe
weekly_cases <- function (df) {
    df %>%
        arrange(facility, date) %>%
        group_by(facility)  %>%
        filter(row_number() %% 7 == 1)
}

#calculate weekly incidence
#df is the output from weekly_cases()
#save as new dataframe
incidence <- function(df) {
    new <- df %>%
        arrange(facility, date) %>%
        group_by(facility) %>%
        mutate(incidence = cummulative_cases - lag(cummulative_cases, default = cummulative_cases[1]))
    invisible(new)
}

#calculate incidence normalized by population size
#df is the output of incidence() with population size data added (available from "all_cases.csv" in this repository)
#save as new dataframe
normbypop <- function(df) {
    norms <- df %>%
        mutate(normalized_incidence = (incidence/pop_est))
    invisible(norms)
}

#identify outbreaks
#outbreak defined as any time at least X% (as specified by threshold, default = 10%) of the population gets infected within a 3 week window
#unique outbreak is first time that an outbreak occurs (when "outbreak" switches from FALSE to TRUE)
#df is weekly case list generated as the output of normbypop()
#save result as new dataframe
find_outbreak <- function(df, threshold = 0.1) {
    outbreaks <- df %>%
        group_by(facility) %>%
        mutate(week3_total = (normalized_incidence + lag(normalized_incidence, n=1, default = incidence[1]) + lag(normalized_incidence, n=2, default = incidence[1]))) %>%
        mutate(outbreak = (week3_total >= threshold)) %>%
        mutate(unique_outbreak = if_else((outbreak == TRUE & (outbreak != lag(outbreak, n=1, default = outbreak[1]))), TRUE, FALSE))
    invisible(outbreaks)
}

#get summary information about the data generated by outbreaks()
#this is the code that was used to generate "summary_data.csv" from "all_cases.csv"
summary_full <- function(df) {
    newdf <- df %>%
        arrange(facility, date) %>%
        group_by(facility) %>%
        summarise(start_date = first(date),
                  end_date = last(date),
                  weeks_of_data = daysbetween(end_date, start_date)/7, 
                  operator = first(operator_class),
                  type = first(type_class),
                  state = first(state),
                  avg_pop = mean(pop_est),
                  max_pop = max(pop_est),
                  min_pop = min(pop_est),
                  pop_change_percent = round(((min_pop - max_pop)/max_pop)*100),
                  vax_timing = first(vax_timing),
                  community_vax_rate = first(community_vax_rate),
                  political_leaning = first(political_leaning),
                  any_outbreak = (sum(unique_outbreak) > 0),
                  unique_outbreaks = sum(unique_outbreak),
                  unique_outbreaks_perweeksdata = (sum(unique_outbreak)/weeks_of_data),
                  outbreak_weeks = sum(outbreak),
                  outbreak_weeks_percent = (outbreak_weeks/weeks_of_data)*100,
                  max_incidence_normalized = max(normalized_incidence),
                  max_incidence_percent = max_incidence_normalized*100)
    newdf$vax_timing <- as.factor(newdf$vax_timing)
    newdf$community_vax_rate <- as.factor(newdf$community_vax_rate)
    newdf$political_leaning <- as.factor(newdf$political_leaning)
    invisible(newdf)
}

#statistical analysis can be performed with wilcox.test() and fisher.test()